// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/contrib/registry/nacos/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/the-zion/matrix-core/app/achievement/service/internal/biz"
	"github.com/the-zion/matrix-core/app/achievement/service/internal/conf"
	"github.com/the-zion/matrix-core/app/achievement/service/internal/data"
	"github.com/the-zion/matrix-core/app/achievement/service/internal/server"
	"github.com/the-zion/matrix-core/app/achievement/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *nacos.Registry) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	cmdable := data.NewRedis(confData, logger)
	achievementMqPro := data.NewRocketmqAchievementProducer(confData, logger)
	dataData, cleanup, err := data.NewData(db, cmdable, achievementMqPro, logger)
	if err != nil {
		return nil, nil, err
	}
	achievementRepo := data.NewAchievementRepo(dataData, logger)
	recovery := data.NewRecovery(dataData)
	transaction := data.NewTransaction(dataData)
	achievementUseCase := biz.NewAchievementUseCase(achievementRepo, recovery, transaction, logger)
	achievementService := service.NewAchievementService(achievementUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, achievementService, logger)
	grpcServer := server.NewGRPCServer(confServer, achievementService, logger)
	app := newApp(logger, registry, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
