// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknownError(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AchievementErrorReason_UNKNOWN_ERROR.String() && e.Code == 500
}

func ErrorUnknownError(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AchievementErrorReason_UNKNOWN_ERROR.String(), fmt.Sprintf(format, args...))
}

func IsSendAchievementAgreeFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AchievementErrorReason_SEND_ACHIEVEMENT_AGREE_FAILED.String() && e.Code == 500
}

func ErrorSendAchievementAgreeFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AchievementErrorReason_SEND_ACHIEVEMENT_AGREE_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsSendAchievementViewFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AchievementErrorReason_SEND_ACHIEVEMENT_VIEW_FAILED.String() && e.Code == 500
}

func ErrorSendAchievementViewFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AchievementErrorReason_SEND_ACHIEVEMENT_VIEW_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsSendAchievementCollectFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AchievementErrorReason_SEND_ACHIEVEMENT_COLLECT_FAILED.String() && e.Code == 500
}

func ErrorSendAchievementCollectFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AchievementErrorReason_SEND_ACHIEVEMENT_COLLECT_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsCancelAchievementAgreeFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == AchievementErrorReason_CANCEL_ACHIEVEMENT_AGREE_FAILED.String() && e.Code == 500
}

func ErrorCancelAchievementAgreeFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, AchievementErrorReason_CANCEL_ACHIEVEMENT_AGREE_FAILED.String(), fmt.Sprintf(format, args...))
}
